#Label Instruction
FROM alpine:3

LABEL nama="I Putu Fardeen Bagas Mahottama"
LABEL nim="2205551112" kelas="Manajemen Jaringan dan Server (E)"

RUN mkdir uas
RUN echo "UAS Fardeen" > "uas/mjs.txt"

CMD cat "uas/mjs.txt"